### ISSUE TITLE
events.js:352 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by rianfloo** [krjo/shopify-webpack-dev-workflow#28]
Hi krjo

I've go an error when running yarn start / npm start at the end of the build. It was perfectly for months. Is there any package update to do?

Thanks a lot :)

```Build Complete 📦
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn theme ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn theme',
  path: 'theme',
  spawnargs: [ 'watch' ]
}
error Command failed with exit code 1.```

**Comment by rianfloo** [comment]
Any news :) ?

**Comment by krjo** [comment]
Check all your npm package versions compared to the versions in this repo and maybe reset and update one by one to see where the issue started.
